--liquibase formatted sql
--changeset codex:1765600000001 splitStatements:false endDelimiter:$$

INSERT INTO book_narrative_beats (
    id, book_id, start_page, end_page, phase, beat_title, plot_state, characters_json, quizzes_json,
    achievement_code, achievement_title, achievement_description, flashcard_symbol
)
SELECT
    uuid_generate_v4(),
    b.id,
    v.start_page,
    v.end_page,
    v.phase,
    v.beat_title,
    v.plot_state,
    v.characters_json,
    v.quizzes_json,
    v.achievement_code,
    v.achievement_title,
    v.achievement_description,
    v.flashcard_symbol
FROM (
    VALUES
    ('9780451524935', 1, 110, 'BEGINNING', 'Vigilância cotidiana',
     'Winston vive sob observação constante e começa a desconfiar da verdade oficial.',
     '[{"name":"Winston Smith","role":"PROTAGONIST","note":"Funcionário que questiona o controle do Partido."},{"name":"Grande Irmão","role":"ANTAGONIST","note":"Símbolo do poder que vigia e intimida a sociedade."}]',
     '[{"id":"1984-b1-q1","question":"O que marca o início da narrativa?","options":["Liberdade plena","Vigilância constante","Viagem espacial","Humor leve"],"correctOption":"Vigilância constante","explanation":"O início apresenta uma sociedade monitorada pelo Partido."}]',
     '1984_VIGILANCIA', 'Olhar atento', 'Identificou o controle social que estrutura a obra.', 'EYE'),
    ('9780451524935', 111, 230, 'MIDDLE', 'Resistência íntima',
     'Winston busca uma brecha emocional e política em meio ao medo de ser descoberto.',
     '[{"name":"Julia","role":"ALLY","note":"Aproxima Winston de uma forma pessoal de resistência."},{"name":"OBrien","role":"MENTOR","note":"Figura ambígua que parece oferecer caminho contra o Partido."}]',
     '[{"id":"1984-b2-q1","question":"Qual tensão cresce no meio da obra?","options":["Conformidade tranquila","Resistência secreta","Fim do Partido","Ausência de medo"],"correctOption":"Resistência secreta","explanation":"Winston tenta resistir sem chamar a atenção do sistema."}]',
     NULL, NULL, NULL, NULL),
    ('9780451524935', 231, 328, 'CLIMAX', 'Quebra da verdade',
     'O poder do Partido se revela total ao transformar memória, afeto e linguagem em instrumentos de domínio.',
     '[{"name":"Winston Smith","role":"PROTAGONIST","note":"Enfrenta o limite entre convicção pessoal e coerção."},{"name":"OBrien","role":"ANTAGONIST","note":"Conduz a demonstração mais dura do poder do Partido."}]',
     '[{"id":"1984-b3-q1","question":"No clímax, o Partido demonstra domínio sobre o quê?","options":["Apenas economia","Memória e verdade","Somente fronteiras","Tecnologia médica"],"correctOption":"Memória e verdade","explanation":"A força do Partido está em controlar o que as pessoas aceitam como real."}]',
     '1984_VERDADE_PARTIDA', 'Verdade sob pressão', 'Compreendeu como poder e linguagem moldam a realidade.', 'EYE'),

    ('9788595084865', 1, 32, 'BEGINNING', 'Encontro no deserto',
     'O narrador conhece o Pequeno Príncipe e percebe que a imaginação infantil revela verdades esquecidas.',
     '[{"name":"Pequeno Príncipe","role":"PROTAGONIST","note":"Viajante sensível que observa o mundo com espanto."},{"name":"Aviador","role":"ALLY","note":"Narrador que aprende a reenxergar o essencial."}]',
     '[{"id":"principe-b1-q1","question":"O que o encontro inicial valoriza?","options":["Pressa adulta","Olhar sensível","Guerra política","Competição"],"correctOption":"Olhar sensível","explanation":"A obra contrasta a visão adulta com a sensibilidade do personagem."}]',
     'PRINCIPE_OLHAR', 'Olhar essencial', 'Entrou na lógica poética do encontro no deserto.', 'STAR'),
    ('9788595084865', 33, 72, 'MIDDLE', 'Planetas e espelhos',
     'As visitas a diferentes mundos revelam vaidade, poder, repetição e solidão em formas simples.',
     '[{"name":"Rosa","role":"ALLY","note":"Representa afeto, cuidado e responsabilidade."},{"name":"Raposa","role":"MENTOR","note":"Ensina que vínculo exige tempo e presença."}]',
     '[{"id":"principe-b2-q1","question":"Qual ideia a Raposa ensina?","options":["Cativar cria responsabilidade","Viajar resolve tudo","Mandar é amar","Esquecer é crescer"],"correctOption":"Cativar cria responsabilidade","explanation":"A Raposa mostra que laços tornam alguém único para nós."}]',
     NULL, NULL, NULL, NULL),
    ('9788595084865', 73, 96, 'CLIMAX', 'O essencial invisível',
     'A despedida reforça que o valor das relações não está apenas no que pode ser visto.',
     '[{"name":"Pequeno Príncipe","role":"PROTAGONIST","note":"Escolhe retornar ao que ama."},{"name":"Aviador","role":"ALLY","note":"Guarda a experiência como memória transformadora."}]',
     '[{"id":"principe-b3-q1","question":"O que sintetiza o final da obra?","options":["O essencial é invisível aos olhos","Tudo é cálculo","Laços não importam","O mundo é simples"],"correctOption":"O essencial é invisível aos olhos","explanation":"A frase resume a importância do vínculo e da sensibilidade."}]',
     'PRINCIPE_ESSENCIAL', 'Essencial guardado', 'Compreendeu a mensagem central sobre afeto e presença.', 'FOX'),

    ('9788583862062', 1, 85, 'BEGINNING', 'Memória em disputa',
     'Bentinho reconstrói sua juventude tentando organizar lembranças, suspeitas e afetos.',
     '[{"name":"Bentinho","role":"PROTAGONIST","note":"Narrador que conduz a memória de forma parcial."},{"name":"Capitu","role":"ALLY","note":"Figura central do afeto e da dúvida do narrador."}]',
     '[{"id":"casmurro-b1-q1","question":"O que marca a voz narrativa no início?","options":["Neutralidade total","Memória subjetiva","Relato científico","Ação policial"],"correctOption":"Memória subjetiva","explanation":"Bentinho narra a partir de lembranças e interpretações próprias."}]',
     'CASMURRO_MEMORIA', 'Memória desconfiada', 'Percebeu que o narrador também precisa ser interpretado.', 'EYES'),
    ('9788583862062', 86, 180, 'MIDDLE', 'Afeto e suspeita',
     'A relação entre Bentinho e Capitu se fortalece enquanto sinais ambíguos alimentam insegurança.',
     '[{"name":"Capitu","role":"PROTAGONIST","note":"Personagem inteligente e enigmática aos olhos do narrador."},{"name":"Escobar","role":"ALLY","note":"Amigo cuja presença ganha peso na suspeita de Bentinho."}]',
     '[{"id":"casmurro-b2-q1","question":"Qual força cresce no meio da narrativa?","options":["Confiança absoluta","Suspeita crescente","Aventura fantástica","Esquecimento completo"],"correctOption":"Suspeita crescente","explanation":"A leitura acompanha como a dúvida passa a dominar Bentinho."}]',
     NULL, NULL, NULL, NULL),
    ('9788583862062', 181, 256, 'CLIMAX', 'Dúvida sem sentença',
     'A narrativa chega ao ponto em que ciúme, memória e interpretação deixam o leitor sem confirmação definitiva.',
     '[{"name":"Bentinho","role":"PROTAGONIST","note":"Transforma lembrança em acusação."},{"name":"Capitu","role":"PROTAGONIST","note":"Permanece como figura interpretada mais do que comprovada."}]',
     '[{"id":"casmurro-b3-q1","question":"Qual é o efeito principal do final?","options":["Prova definitiva","Dúvida persistente","Final de aventura","Reconciliação simples"],"correctOption":"Dúvida persistente","explanation":"O romance mantém a ambiguidade como parte essencial da leitura."}]',
     'CASMURRO_DUVIDA', 'Dúvida literária', 'Reconheceu a ambiguidade como força central da obra.', 'MASK'),

    ('9788532530802', 1, 88, 'BEGINNING', 'Carta para Hogwarts',
     'Harry descobre que pertence a um mundo mágico e que sua história é maior do que imaginava.',
     '[{"name":"Harry Potter","role":"PROTAGONIST","note":"Menino que descobre sua identidade bruxa."},{"name":"Hagrid","role":"MENTOR","note":"Abre a porta para o mundo mágico."}]',
     '[{"id":"hp1-b1-q1","question":"O que muda a vida de Harry no início?","options":["Uma carta de Hogwarts","Um torneio esportivo","Uma viagem comum","Um emprego"],"correctOption":"Uma carta de Hogwarts","explanation":"A carta revela a ligação de Harry com o mundo bruxo."}]',
     'HP_HOGWARTS', 'Porta para Hogwarts', 'Entrou no universo mágico junto com Harry.', 'OWL'),
    ('9788532530802', 89, 190, 'MIDDLE', 'Amizade e mistério',
     'Harry forma alianças em Hogwarts enquanto pistas sobre a Pedra Filosofal aumentam o perigo.',
     '[{"name":"Hermione Granger","role":"ALLY","note":"Usa conhecimento e disciplina para ajudar o grupo."},{"name":"Rony Weasley","role":"ALLY","note":"Oferece amizade e coragem nas descobertas."}]',
     '[{"id":"hp1-b2-q1","question":"O que sustenta Harry no meio da história?","options":["Isolamento","Amizade e curiosidade","Indiferença","Poder político"],"correctOption":"Amizade e curiosidade","explanation":"O trio avança graças à confiança e investigação conjunta."}]',
     NULL, NULL, NULL, NULL),
    ('9788532530802', 191, 264, 'CLIMAX', 'A escolha diante da pedra',
     'O confronto final testa coragem, desejo e a capacidade de proteger algo maior que si mesmo.',
     '[{"name":"Harry Potter","role":"PROTAGONIST","note":"Enfrenta o perigo com coragem."},{"name":"Voldemort","role":"ANTAGONIST","note":"Ameaça que retorna por trás do mistério."}]',
     '[{"id":"hp1-b3-q1","question":"O que o clímax testa em Harry?","options":["Vaidade","Coragem e escolha","Sono","Riqueza"],"correctOption":"Coragem e escolha","explanation":"Harry precisa agir sem buscar benefício próprio."}]',
     'HP_PEDRA', 'Guardião da pedra', 'Concluiu o arco inicial de coragem em Hogwarts.', 'SCAR'),

    ('9780441172719', 1, 230, 'BEGINNING', 'Casa em risco',
     'Paul Atreides chega a Arrakis cercado por política, profecias e ameaça de traição.',
     '[{"name":"Paul Atreides","role":"PROTAGONIST","note":"Herdeiro treinado para sobreviver a jogos políticos."},{"name":"Duque Leto","role":"MENTOR","note":"Pai e líder que tenta proteger sua casa."}]',
     '[{"id":"duna-b1-q1","question":"Qual tensão domina o início de Duna?","options":["Política e sobrevivência","Comédia familiar","Viagem turística","Paz garantida"],"correctOption":"Política e sobrevivência","explanation":"Arrakis é apresentado como centro de disputa e perigo."}]',
     'DUNA_ARRAKIS', 'Chegada a Arrakis', 'Entendeu o peso político do planeta deserto.', 'SPICE'),
    ('9780441172719', 231, 520, 'MIDDLE', 'Deserto e adaptação',
     'A queda dos Atreides obriga Paul a aprender com o deserto e com os Fremen.',
     '[{"name":"Chani","role":"ALLY","note":"Conecta Paul ao modo de vida Fremen."},{"name":"Barão Harkonnen","role":"ANTAGONIST","note":"Representa a força política inimiga."}]',
     '[{"id":"duna-b2-q1","question":"O que Paul precisa aprender no meio da obra?","options":["Ignorar o deserto","Adaptar-se aos Fremen","Abandonar toda estratégia","Confiar nos Harkonnen"],"correctOption":"Adaptar-se aos Fremen","explanation":"Sua sobrevivência depende de compreender Arrakis por dentro."}]',
     NULL, NULL, NULL, NULL),
    ('9780441172719', 521, 688, 'CLIMAX', 'Profecia e poder',
     'Paul transforma sobrevivência em liderança, mas cada vitória carrega consequências políticas e religiosas.',
     '[{"name":"Paul Atreides","role":"PROTAGONIST","note":"Assume poder com consciência do risco histórico."},{"name":"Fremen","role":"ALLY","note":"Povo do deserto que redefine o destino de Arrakis."}]',
     '[{"id":"duna-b3-q1","question":"Qual dilema marca o clímax?","options":["Poder sem consequência","Liderança e destino coletivo","Esquecimento total","Fim da religião"],"correctOption":"Liderança e destino coletivo","explanation":"A ascensão de Paul afeta muito mais que sua trajetória pessoal."}]',
     'DUNA_MUADDIB', 'Destino no deserto', 'Compreendeu a virada de Paul em Arrakis.', 'DESERT'),

    ('9780262035613', 1, 255, 'BEGINNING', 'Fundamentos da aprendizagem',
     'A leitura apresenta conceitos de representação, otimização e generalização como base para redes neurais.',
     '[{"name":"Representações","role":"PROTAGONIST","note":"Transformam dados brutos em padrões aprendíveis."},{"name":"Overfitting","role":"ANTAGONIST","note":"Ameaça quando o modelo memoriza em vez de generalizar."}]',
     '[{"id":"deep-b1-q1","question":"Qual preocupação aparece nos fundamentos?","options":["Generalização","Romance histórico","Magia ritual","Narrador não confiável"],"correctOption":"Generalização","explanation":"Modelos úteis precisam funcionar além dos exemplos vistos."}]',
     'DEEP_FUNDAMENTOS', 'Base neural', 'Reconheceu os fundamentos que sustentam aprendizagem profunda.', 'NET'),
    ('9780262035613', 256, 540, 'MIDDLE', 'Arquiteturas e treinamento',
     'O meio da obra aprofunda redes, regularização e escolhas de treinamento para problemas complexos.',
     '[{"name":"Regularização","role":"ALLY","note":"Ajuda a controlar excesso de ajuste."},{"name":"Gradiente instável","role":"ANTAGONIST","note":"Dificulta treinamento eficiente em redes profundas."}]',
     '[{"id":"deep-b2-q1","question":"O que ajuda a reduzir overfitting?","options":["Regularização","Memorização cega","Remover validação","Ignorar dados"],"correctOption":"Regularização","explanation":"Regularização ajuda o modelo a generalizar melhor."}]',
     NULL, NULL, NULL, NULL),
    ('9780262035613', 541, 775, 'CLIMAX', 'Aplicações profundas',
     'A parte final conecta técnicas a visão computacional, linguagem e desafios práticos de sistemas inteligentes.',
     '[{"name":"Modelos profundos","role":"PROTAGONIST","note":"Aplicam camadas de representação a tarefas complexas."},{"name":"Dados ruins","role":"ANTAGONIST","note":"Limitam qualidade mesmo quando a arquitetura é forte."}]',
     '[{"id":"deep-b3-q1","question":"Qual mensagem prática fecha melhor a leitura?","options":["Modelo depende de dados e validação","Arquitetura resolve tudo","Teste não importa","Dados são sempre neutros"],"correctOption":"Modelo depende de dados e validação","explanation":"Aplicações reais exigem técnica, dados adequados e avaliação cuidadosa."}]',
     'DEEP_APLICACOES', 'Rede aplicada', 'Conectou fundamentos a aplicações reais de deep learning.', 'NET'),

    ('9780132350884', 1, 155, 'BEGINNING', 'Código legível',
     'A leitura começa pela ideia de que nomes, funções e organização comunicam intenção.',
     '[{"name":"Desenvolvedor","role":"PROTAGONIST","note":"Responsável por tornar o código compreensível."},{"name":"Código confuso","role":"ANTAGONIST","note":"Representa custo, retrabalho e risco técnico."}]',
     '[{"id":"clean-b1-q1","question":"Qual princípio aparece no início?","options":["Código comunica intenção","Nomes não importam","Funções devem crescer sempre","Testes são ruído"],"correctOption":"Código comunica intenção","explanation":"A obra defende legibilidade como parte do design."}]',
     'CLEAN_LEGIBILIDADE', 'Leitura limpa', 'Reconheceu legibilidade como requisito técnico.', 'CODE'),
    ('9780132350884', 156, 330, 'MIDDLE', 'Funções e testes',
     'O foco passa para pequenas unidades de comportamento, redução de duplicação e confiança por testes.',
     '[{"name":"Teste automatizado","role":"ALLY","note":"Sustenta mudanças com segurança."},{"name":"Duplicação","role":"ANTAGONIST","note":"Aumenta manutenção e inconsistência."}]',
     '[{"id":"clean-b2-q1","question":"O que aumenta confiança para mudar código?","options":["Testes automatizados","Duplicação","Nomes vagos","Funções enormes"],"correctOption":"Testes automatizados","explanation":"Testes dão feedback rápido sobre comportamento."}]',
     NULL, NULL, NULL, NULL),
    ('9780132350884', 331, 464, 'CLIMAX', 'Refinamento contínuo',
     'A mensagem final reforça que qualidade nasce de revisão constante, disciplina e cuidado coletivo.',
     '[{"name":"Refatoração","role":"ALLY","note":"Melhora estrutura sem mudar comportamento esperado."},{"name":"Dívida técnica","role":"ANTAGONIST","note":"Acumula dificuldade quando o cuidado é adiado."}]',
     '[{"id":"clean-b3-q1","question":"Qual prática resume o cuidado final?","options":["Refatorar com segurança","Ignorar testes","Acumular dívida","Evitar revisão"],"correctOption":"Refatorar com segurança","explanation":"A melhoria contínua mantém o sistema saudável."}]',
     'CLEAN_REFINO', 'Refino constante', 'Compreendeu que código limpo é prática contínua.', 'TOOLS'),

    ('9780735211292', 1, 105, 'BEGINNING', 'Pequenas mudanças',
     'O livro apresenta hábitos como sistemas repetidos, não como decisões isoladas de motivação.',
     '[{"name":"Identidade","role":"PROTAGONIST","note":"Base para construir hábitos coerentes."},{"name":"Motivação instável","role":"ANTAGONIST","note":"Falha quando depende apenas de vontade momentânea."}]',
     '[{"id":"habitos-b1-q1","question":"Qual ideia abre a obra?","options":["Hábitos são sistemas","Motivação resolve tudo","Mudança precisa ser gigante","Rotina não importa"],"correctOption":"Hábitos são sistemas","explanation":"Pequenas ações repetidas moldam resultados maiores."}]',
     'HABITOS_SISTEMA', 'Sistema iniciado', 'Entendeu a força das pequenas repetições.', 'ATOM'),
    ('9780735211292', 106, 225, 'MIDDLE', 'Ambiente e repetição',
     'A leitura aprofunda gatilhos, recompensas e ambiente como peças para tornar hábitos mais naturais.',
     '[{"name":"Ambiente","role":"ALLY","note":"Ajuda ou dificulta a repetição de comportamentos."},{"name":"Atrito","role":"ANTAGONIST","note":"Impede ações desejadas quando o sistema é mal desenhado."}]',
     '[{"id":"habitos-b2-q1","question":"O que facilita um bom hábito?","options":["Reduzir atrito","Aumentar confusão","Esconder pistas","Depender só de força"],"correctOption":"Reduzir atrito","explanation":"Quanto mais fácil a ação, maior a chance de repetição."}]',
     NULL, NULL, NULL, NULL),
    ('9780735211292', 226, 320, 'CLIMAX', 'Identidade em prática',
     'O fechamento conecta consistência, revisão e identidade para manter hábitos ao longo do tempo.',
     '[{"name":"Consistência","role":"ALLY","note":"Mantém o sistema mesmo quando a motivação oscila."},{"name":"Perfeccionismo","role":"ANTAGONIST","note":"Transforma pequenos deslizes em desistência."}]',
     '[{"id":"habitos-b3-q1","question":"O que sustenta hábitos no longo prazo?","options":["Identidade e consistência","Perfeição imediata","Pressa constante","Ausência de revisão"],"correctOption":"Identidade e consistência","explanation":"A prática se mantém melhor quando ligada a quem a pessoa quer se tornar."}]',
     'HABITOS_IDENTIDADE', 'Identidade em ação', 'Conectou hábitos à construção de identidade.', 'ATOM'),

    ('9788576849949', 1, 110, 'BEGINNING', 'Duas mentalidades',
     'A obra contrapõe formas diferentes de pensar dinheiro, trabalho e educação financeira.',
     '[{"name":"Pai Rico","role":"MENTOR","note":"Representa visão empreendedora e foco em ativos."},{"name":"Pai Pobre","role":"MENTOR","note":"Representa segurança tradicional e dependência salarial."}]',
     '[{"id":"pai-rico-b1-q1","question":"Qual contraste inicia o livro?","options":["Duas mentalidades financeiras","Mistério policial","Fantasia épica","Viagem espacial"],"correctOption":"Duas mentalidades financeiras","explanation":"O livro nasce do contraste entre duas formas de pensar dinheiro."}]',
     'PAI_RICO_MENTALIDADE', 'Mentalidade financeira', 'Identificou o contraste central da obra.', 'COIN'),
    ('9788576849949', 111, 235, 'MIDDLE', 'Ativos e escolhas',
     'A leitura enfatiza diferença entre ativos, passivos e decisões que afetam liberdade financeira.',
     '[{"name":"Ativos","role":"ALLY","note":"Geram recursos e aumentam autonomia."},{"name":"Passivos disfarçados","role":"ANTAGONIST","note":"Parecem progresso, mas elevam dependência."}]',
     '[{"id":"pai-rico-b2-q1","question":"Qual conceito ganha força no meio da obra?","options":["Ativos e passivos","Magia antiga","Ciúme romântico","Guerra medieval"],"correctOption":"Ativos e passivos","explanation":"O livro usa essa diferença para discutir decisões financeiras."}]',
     NULL, NULL, NULL, NULL),
    ('9788576849949', 236, 336, 'CLIMAX', 'Autonomia financeira',
     'O fechamento reforça educação contínua, iniciativa e responsabilidade sobre escolhas financeiras.',
     '[{"name":"Educação financeira","role":"ALLY","note":"Ajuda a tomar decisões com mais autonomia."},{"name":"Medo de arriscar","role":"ANTAGONIST","note":"Pode bloquear aprendizado e ação."}]',
     '[{"id":"pai-rico-b3-q1","question":"Qual mensagem fecha melhor a obra?","options":["Aprender continuamente","Evitar toda decisão","Gastar sem controle","Depender apenas do salário"],"correctOption":"Aprender continuamente","explanation":"A obra reforça ação, estudo e responsabilidade financeira."}]',
     'PAI_RICO_AUTONOMIA', 'Autonomia em construção', 'Compreendeu a ideia de educação financeira contínua.', 'COIN')
) AS v(
    isbn, start_page, end_page, phase, beat_title, plot_state, characters_json, quizzes_json,
    achievement_code, achievement_title, achievement_description, flashcard_symbol
)
JOIN books b ON b.isbn = v.isbn
ON CONFLICT (book_id, start_page) DO NOTHING;
$$
